// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9hTpCm_uOwyg2AfKaQrgCPdiG3hwJwPc',
    appId: '1:426258127319:web:659b4e674880a2118b9392',
    messagingSenderId: '426258127319',
    projectId: 'zindagi-c5cf1',
    authDomain: 'zindagi-c5cf1.firebaseapp.com',
    storageBucket: 'zindagi-c5cf1.appspot.com',
    measurementId: 'G-BTP6FGTKRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7BHrCYJbdCaj00wxIA3roS8i3OIP3ZW4',
    appId: '1:426258127319:android:fe01122d6356c5d68b9392',
    messagingSenderId: '426258127319',
    projectId: 'zindagi-c5cf1',
    storageBucket: 'zindagi-c5cf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm0IFCK8tJ98f0OtBGy4ZjX6oaGp8TGHQ',
    appId: '1:426258127319:ios:f132008213a43ce08b9392',
    messagingSenderId: '426258127319',
    projectId: 'zindagi-c5cf1',
    storageBucket: 'zindagi-c5cf1.appspot.com',
    iosBundleId: 'com.example.bloodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm0IFCK8tJ98f0OtBGy4ZjX6oaGp8TGHQ',
    appId: '1:426258127319:ios:98bb424d1bc5581d8b9392',
    messagingSenderId: '426258127319',
    projectId: 'zindagi-c5cf1',
    storageBucket: 'zindagi-c5cf1.appspot.com',
    iosBundleId: 'com.example.bloodapp.RunnerTests',
  );
}
